{
 "title": "Synology",
 "description": "A Dashboard to monitor Synology NAS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "diskstation",
    "label": "Disk Station",
    "query": "show tag values from \"snmp.SYNO\" with key=\"agent_host\""
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": "show tag values from \"raidTable\" with key=\"raidName\" where \"agent_host\" =~ /$diskstation/"
   },
   {
    "name": "diskPath",
    "label": "Disk Path",
    "query": "show tag values from \"diskSMARTTable\" with key=\"diskSMARTInfoDevName\" where \"agent_host\" =~ /$diskstation/"
   }
  ]
 },
 "panels": [
  {
   "title": "Raid Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_raidName",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "raidTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT \"raidStatus\" FROM \"raidTable\" WHERE (\"agent_host\" =~ /^$diskstation$/ AND \"raidName\" =~ /^$volume$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "raidStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" },
      { "condition": "AND", "key": "raidName", "operator": "=~", "value": "/^$volume$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System fan status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT \"systemFanStatus\" FROM \"snmp.SYNO\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "systemFanStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "UPS Status",
     "measurement": "ups",
     "query": "SELECT \"upsStatus\" FROM \"ups\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "upsStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "snmp.SYNO",
     "query": "SELECT \"upTime\"  / 100 FROM \"snmp.SYNO\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "upTime" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Synology NAS",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"modelName\") AS \"Synology Model\", last(\"version\") AS \"DSM Version\", last(\"serialNumber\") AS \"Serial Number\" FROM \"snmp.SYNO\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "modelName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Synology Model" ], "type": "alias" }
      ],
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DSM Version" ], "type": "alias" }
      ],
      [
       { "params": [ "serialNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial Number" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU fan status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT \"cpuFanStatus\" FROM \"snmp.SYNO\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter GROUP BY \"agent_host\"",
     "select": [
      [
       { "params": [ "cpuFanStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System overall status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "snmp.SYNO",
     "query": "SELECT \"systemStatus\" FROM \"snmp.SYNO\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "systemStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "measurement": "raidTable",
     "query": "SELECT \"raidTotalSize\" - raidFreeSize FROM \"raidTable\" WHERE (\"raidName\" =~ /^$volume$/ AND \"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "raidTotalSize" ], "type": "field" },
       { "params": [ "- raidFreeSize" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "raidName", "operator": "=~", "value": "/^$volume$/" },
      { "condition": "AND", "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "System temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT \"temperature\" FROM \"snmp.SYNO\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UPS Battery Level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "measurement": "ups",
     "query": "SELECT \"upsBatteryCharge\" FROM \"ups\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "ups",
     "select": [
      [
       { "params": [ "upsLoad" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "ups",
     "select": [
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Run Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "ups",
     "select": [
      [
       { "params": [ "upsBatteryRuntime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "ups",
     "select": [
      [
       { "params": [ "upsBatteryVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Input Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "ups",
     "select": [
      [
       { "params": [ "upsInputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Vs. Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "laNames" ], "type": "tag" }
     ],
     "measurement": "laTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT moving_average(mean(\"laLoadInt\"), 5) FROM \"laTable\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter GROUP BY time($__interval), \"laNames\"",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "snmp.SYNO",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Model & Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"diskModel\") AS \"Model\", last(\"diskStatus\") AS \"Status\", last(\"diskType\") AS \"Disk Type\", last(\"diskTemperature\") AS \"CurrentC\", max(\"diskTemperature\") AS \"MaxC\", min(\"diskTemperature\") AS \"MinC\", \"synology\".\"autogen\".\"diskSMARTTable\".\"diskSMARTAttrRaw\" AS \"MinC\" FROM \"diskTable\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter GROUP BY \"diskID\", \"devicePath\"",
     "select": [
      [
       { "params": [ "diskModel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "diskStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "diskType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Disk Type" ], "type": "alias" }
      ],
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CurrentC" ], "type": "alias" }
      ],
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "MaxC" ], "type": "alias" }
      ],
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "MinC" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_raidName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "raidName" ], "type": "tag" }
     ],
     "measurement": "raidTable",
     "query": "SELECT mean(\"raidTotalSize\") AS \"SizeTotal\", mean(\"raidFreeSize\") AS \"SizeFree\", \"raidTotalSize\" - mean(raidFreeSize) AS \"SizeFree\" FROM \"raidTable\" WHERE (\"agent_host\" =~ /^$diskstation$/) AND $timeFilter GROUP BY time($__interval), \"raidName\"",
     "select": [
      [
       { "params": [ "raidTotalSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "SizeTotal" ], "type": "alias" }
      ],
      [
       { "params": [ "raidFreeSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "SizeFree" ], "type": "alias" }
      ],
      [
       { "params": [ "raidTotalSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- mean(raidFreeSize)" ], "type": "math" },
       { "params": [ "SizeFree" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" },
      { "condition": "AND", "key": "raidName", "operator": "=~", "value": "/^$volume$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups",
     "select": [
      [
       { "params": [ "upsLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UPS Load" ], "type": "alias" }
      ],
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UPS Charge Level" ], "type": "alias" }
      ],
      [
       { "params": [ "upsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UPS Input Voltage" ], "type": "alias" }
      ],
      [
       { "params": [ "upsBatteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UPS Battery Voltage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_storageIODevice - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageIODevice" ], "type": "tag" }
     ],
     "measurement": "storageIOTable",
     "select": [
      [
       { "params": [ "storageIOWrites" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       { "params": [ "storageIOReads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk and System Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_diskID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "select": [
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "snmp.SYNO",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" }
     ]
    }
   ]
  },
  {
   "title": "SMART Info",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "diskSMARTInfoDevName" ], "type": "tag" },
      { "params": [ "diskSMARTAttrId" ], "type": "tag" }
     ],
     "measurement": "diskSMARTTable",
     "select": [
      [
       { "params": [ "diskSMARTAttrCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Value" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSMARTAttrName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Attribute" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSMARTAttrRaw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Raw Data" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSMARTAttrStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSMARTAttrThreshold" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Threshold" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSMARTAttrWorst" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Worst" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" },
      { "condition": "AND", "key": "diskSMARTInfoDevName", "operator": "=~", "value": "/^$diskPath$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifDescr - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" }
     ],
     "measurement": "ifTable",
     "query": "SELECT mean(\"value\") FROM \"ifTable\" WHERE (\"agent_host\" = '192.168.1.5') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Down" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Up" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$diskstation$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "!=", "value": "docker0" },
      { "condition": "AND", "key": "ifDescr", "operator": "!=", "value": "sit0" }
     ]
    }
   ]
  }
 ]
}